##
## ----------------------------------------
##
## Red Hat Openshift & CoreOS Sources
##

ocp_assets:

  "4_6":
    name:        "openshift"
    version:     "4.6"
    url:         "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.6.1"
    install_tar: "openshift-install-linux-4.6.1.tar.gz"
    client_tar:  "openshift-client-linux-4.6.1.tar.gz"

  "4_5":
    name:        "openshift"
    version:     "4.5"
    url:         "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.5.2"
    install_tar: "openshift-install-linux-4.5.2.tar.gz"
    client_tar:  "openshift-client-linux-4.5.2.tar.gz"

  "4_4":
    name:        "openshift"
    version:     "4.4"
    url:         "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.4.12"
    install_tar: "openshift-install-linux-4.4.12.tar.gz"
    client_tar:  "openshift-client-linux-4.4.12.tar.gz"

  "4_3":
    name:        "openshift"
    version:     "4.3"
    url:         "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.3.0"
    install_tar: "openshift-install-linux-4.3.0.tar.gz"
    client_tar:  "openshift-client-linux-4.3.0.tar.gz"

  "4_2":
    name:        "openshift"
    version:     "4.2"
    url:         "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.2.18"
    install_tar: "openshift-install-linux-4.2.18.tar.gz"
    client_tar:  "openshift-client-linux-4.2.18.tar.gz"
rhcos_assets:

  "4_6":
    name:        "rhcos"
    version:     "4.6"
    url:         "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.1"
    initramfs:   "rhcos-4.6.1-x86_64-live-initramfs.x86_64.img"
    rootfs:      "rhcos-4.6.1-x86_64-live-rootfs.x86_64.img"
    kernel:      "rhcos-4.6.1-x86_64-live-kernel-x86_64"
    bios:        "rhcos-4.6.1-x86_64-metal.x86_64.raw.gz"
    iso:         "rhcos-4.6.1-x86_64-live.x86_64.iso"

  "4_5":
    name:        "rhcos"
    version:     "4.5"
    url:         "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.5/4.5.2"
    initramfs:   "rhcos-4.5.2-x86_64-installer-initramfs.x86_64.img"
    kernel:      "rhcos-4.5.2-x86_64-installer-kernel-x86_64"
    bios:        "rhcos-4.5.2-x86_64-metal.x86_64.raw.gz"
    iso:         "rhcos-4.5.2-x86_64-installer.x86_64.iso"

  "4_4":
    name:        "rhcos"
    version:     "4.4"
    url:         "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.4/4.4.3"
    initramfs:   "rhcos-4.4.3-x86_64-installer-initramfs.x86_64.img"
    kernel:      "rhcos-4.4.3-x86_64-installer-kernel-x86_64"
    bios:        "rhcos-4.4.3-x86_64-metal.x86_64.raw.gz"
    iso:         "rhcos-4.4.3-x86_64-installer.x86_64.iso"

  "4_3":
    name:        "rhcos"
    version:     "4.3"
    url:         "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.3/4.3.0"
    initramfs:   "rhcos-4.3.0-x86_64-installer-initramfs.img"
    kernel:      "rhcos-4.3.0-x86_64-installer-kernel"
    bios:        "rhcos-4.3.0-x86_64-metal.raw.gz"
    iso:         "rhcos-4.3.0-x86_64-installer.iso"

  "4_2":
    name:        "rhcos"
    version:     "4.2"
    url:         "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.2/4.2.18"
    initramfs:   "rhcos-4.2.18-x86_64-installer-initramfs.img"
    kernel:      "rhcos-4.2.18-x86_64-installer-kernel"
    bios:        "rhcos-4.2.18-x86_64-metal-bios.raw.gz"
    iso:         "rhcos-4.2.18-x86_64-installer.iso"
