##
##    First character of variable:
##
##     g_Name - global: declared in this file
##
##     h_Name - host: declared in host inventory OR
##                    in a [hostname:vars] block
##
##     p_Name - play: declared as part of a play/task
##



[all:vars]

## ----------------------------------------
##     Openshift Deployment Parameters
##
##     g_clusterVersion 
##     g_wildcardName 
##     g_clusterUser
##     g_credsDir

g_clusterVersion = "4_6"
g_clusterAdmin   = "cloud-admin"
g_clusterUser    = "cloud-user"
g_credsDir       = "/root/ocp-{{ g_clusterName}}"
g_credsDir       = "/root/ocp-{{ g_clusterName}}"
g_wildcardName   = "apps"

##
## ----------------------------------------
## Proxy settings (affects playbooks and openshift config)
##
##   Examples:
##     g_http_proxy = httpProxy: http://<username>:<pswd>@<ip>:<port>
##     g_https_proxy = httpsProxy: http://<username>:<pswd>@<ip>:<port>
##     g_no_proxy = noProxy: example.com

g_http_proxy  = ""
g_https_proxy = ""
g_no_proxy    = ""

## ----------------------------------------
##     Bastion Configuration Parameters
##

g_useDNS          = "True"
g_useDHCP         = "True"
g_usePXE          = "True"
g_useUEFI_HTTP    = "True"
g_useHAPROXY      = "True"
g_useHAPROXY_VIP  = "True"
g_useMATCHBOX     = "True"
g_useNFS          = "True"
g_useNTP          = "True"
g_useDNSwildcard  = "True"

g_nfsExport       = "/home/nfs-{{ g_clusterName }}"

## ----------------------------------------
##    g_clusterName
##
##    used with network basedomain to create 
##    unique network domain for the cluster
##

g_clusterName = "ocp4kvm"

## ----------------------------------------
##    g_clusterVIP
##
##    If you are planning to run a loadbalancer (haproxy)
##    on a host other than the bastion (ie: the virt-host perhaps)
##    specify the cluster virtual IP (VIP).  This is only
##    used to create an additional haproxy.cfg and does
##    not impact the cluster configuration or deployment
##

g_clusterVIP = ""

##
## ----------------------------------------
##    g_network0_*
##
##    Parameters for the default network
##
##    NOTE: sticking with older workshop variable names
##          to preserve compatibility
##

g_publicNet     = "True"
g_publicDomain  = "example.com"
g_pubNET        = "192.168.123.0"
g_pubNM         = "255.255.255.0"
g_pubBC         = "192.168.123.255"
g_pubPREFIX     = "24"
g_pubGW         = "192.168.123.1"
g_pubDNS        = "192.168.123.1"
g_pubNTP        = "192.168.123.160"
g_pubFQDN       = "{{ g_clusterName }}.{{ g_publicDomain }}"

##
## ----------------------------------------
##
## This has the effect of changing the default domainname so
## we won't have to specify FQDN in host vars section below
##

ansible_host = "{{ inventory_hostname }}.{{ g_pubFQDN }}"

##
## ----------------------------------------
##
## h_rhcosDEV : default is 'vda'
##    If RHCOS is not detecting the right boot device, you can be specific
##    by modifying this paramenter (examples: sda, vda, nvmen0)
##
## h_rhcosNIC : default is 'dhcp'
##    If RHCOS is not detecting the right network device, you can be specific
##    by modifying this paramenter (examples: eth0:dhcp, ens3:dhcp, ens192:dhcp)
##
## h_rhcosUSBdelay : default is '0'
##    Some baremetal nodes (ie: HP DL360) have usb storage cards in the LOM
##    that confuses kernel and moves the boot disk around (maybe it's sda, maybe
##    next time it's sdb).  Set this to delay the USB storage scan by X seconds.
##    A good value might be h_rhcosUSBdelay = '10'
##
## ** NOTE **  You can also declare these in the [hostgroup:vars] or for each individual host
##

h_rhcosDEV      = "vda"
h_rhcosNIC      = "dhcp"
h_rhcosUSBdelay = "0"

##
## ----------------------------------------
## HOSTGROUP VARS

[myDeployhost:vars]

ansible_connection=local

## -----------------

[myBastion:vars]

h_hwPROF = "kvm_vda"
h_rsPROF = "bastion"
h_ksPROF = "rhel82-bootiso"

## -----------------

[myBootstrap:vars]

h_hwPROF = "kvm_vda"
h_rsPROF = "med"
h_ksPROF = ""

## -----------------

[myMasters:vars]

h_hwPROF = "kvm_vda"
h_rsPROF = "med"
h_ksPROF = ""

## -----------------

[myWorkers:vars]

h_hwPROF = "kvm_vda"
h_rsPROF = "sml"
h_ksPROF = ""

##
## ----------------------------------------
## HOST VARS

[myDeployhost]
test-amd.lab.linuxsoup.com

[myBastion]
bastion h_pubIP="192.168.123.110"

[myBastion]
bastion   h_pubIP="192.168.123.160"

[myBootstrap]
node1     h_pubIP="192.168.123.161"

[myMasters]
node2     h_pubIP="192.168.123.162" h_etcdName="etcd-0"
node3     h_pubIP="192.168.123.163" h_etcdName="etcd-1"
node4     h_pubIP="192.168.123.164" h_etcdName="etcd-2"

[myWorkers]
node5     h_pubIP="192.168.123.165"
node6     h_pubIP="192.168.123.166"

