## Authors: 
##   Christoph Doerbeck
##
## Summary:
##   This playbook attempts to configure a rhel 8.0 (or later) system with libvirt
##   to host an openshift 4.2 deployment
##
##   This playbook is NOT meant for student execution  
##
##   This playbook IS meant for someone who'd like to stand up Openshift on a single node
##
## Playbook Assumptions:
##     #1 you are executing this on the OS already installed on bare-metal
##     #2 your host is registered to RH CDN with subscription-manager
##     #3 the following packages have been installed: git, ansible
##     #4 system has plenty of storage and memory
##

---
- hosts: myVirthost

  tasks:

  - include_vars: "{{ item }}"
    with_first_found: "{{ vars_libvirt }}"


  - name: "LIBVIRT-SETUP: test existence of libvirt network ({{ kvm_cfg.network.name }})"
    shell: 
      cmd: |
        virsh net-info "{{ kvm_cfg.network.name }}"
    ignore_errors: yes
    register: test_libvirt_network

  - debug: msg="Libvirt Network Test Result Code = {{ test_libvirt_network.rc }}"

  - name: "LIBVIRT-SETUP: test for valid network.fwd_type ({{ kvm_cfg.network.fwd_type }})"
    fail: msg="currently only support network.fwd_type = [ nat | bridge ]"
    when:
      - kvm_cfg.network.fwd_type != "nat" 
      - kvm_cfg.network.fwd_type != "bridge"


  ## ----- NAT NETWORK

  - name: "LIBVIRT-SETUP: deploy xml template for nat network ({{ kvm_cfg.network.name }})"
    when: kvm_cfg.network.fwd_type == "nat"
    vars:
      - p_name:    "{{ kvm_cfg.network.name }}"
      - p_type:    "{{ kvm_cfg.network.fwd_type }}"
      - p_address: "{{ g_pubGW }}"
      - p_netmask: "{{ g_pubNM }}"
    template:
      src: "libvirt-net-nat.j2"
      dest: "/var/tmp/libvirt-network.xml"
      owner: root
      group: root
      mode: 0644

  ## ----- BRIDGE NETWORK requires that bridge interface is created

  - name: "LIBVIRT-SETUP: deploy xml template for libvirt bridged network ({{ kvm_cfg.network.name }})"
    when: kvm_cfg.network.fwd_type == "bridge"
    vars:
      - p_name:    "{{ kvm_cfg.network.name }}"
      - p_type:    "{{ kvm_cfg.network.fwd_type }}"
      - p_address: "{{ hostvars[item]['h_pubIP'] }}"
      - p_netmask: "{{ g_pubNM }}"
    template:
      src: "libvirt-net-bridge.j2"
      dest: "/var/tmp/libvirt-network.xml"
      owner: root
      group: root
      mode: 0644
    loop: "{{ groups['myVirthost'] }}"

  - name: "LIBVIRT-SETUP: test existence of network bridge ({{ kvm_cfg.network.bridge }})"
    when: 
      - kvm_cfg.network.fwd_type == "bridge"
      - test_libvirt_network.rc != 0
    shell: 
      cmd: |
        nmcli dev show "{{ kvm_cfg.network.bridge }}"
    ignore_errors: yes
    register: test_bridge_network

  - debug: msg="Bridge Network Test Result Code = {{ test_bridge_network.rc }}"
    when: 
      - kvm_cfg.network.fwd_type == "bridge"
      - test_libvirt_network.rc != 0

  - name: "LIBVIRT-SETUP: create bridge device ({{ kvm_cfg.network.name }})"
    when: 
      - kvm_cfg.network.fwd_type == "bridge"
      - test_libvirt_network.rc != 0 
      - test_bridge_network.rc != 0
    shell:
      cmd: |
        nmcli con add type bridge \
              con-name {{ kvm_cfg.network.bridge }} \
              ifname   {{ kvm_cfg.network.bridge }} \
              ip4      {{ kvm_cfg.network.ipv4.addr }} \
              gw4      {{ kvm_cfg.network.ipv4.gw }} \
              ipv4.dns {{ g_pubDNS }} \
              autoconnect yes bridge.stp no ipv6.method ignore

  - name: "LIBVIRT-SETUP: add device to bridge ({{ kvm_cfg.network.name }})"
    when: 
      - kvm_cfg.network.fwd_type == "bridge"
      - test_libvirt_network.rc != 0 
      - test_bridge_network.rc != 0
    shell:
      cmd: |
        nmcli con add type ethernet con-name {{ kvm_cfg.network.dev }} ifname {{ kvm_cfg.network.dev }} master {{ kvm_cfg.network.bridge }}
        nmcli con modify {{ kvm_cfg.network.bridge }} connection.autoconnect-slaves yes

  - name: "LIBVIRT-SETUP: bring up bridge ({{ kvm_cfg.network.name }})"
    when: 
      - kvm_cfg.network.fwd_type == "bridge"
      - test_libvirt_network.rc != 0 
      - test_bridge_network.rc != 0
    shell: 
      cmd: |
        ifdown {{ kvm_cfg.network.dev }}
        ifdown {{ kvm_cfg.network.bridge }}
        ifup   {{ kvm_cfg.network.bridge }}

  - name: "LIBVIRT-SETUP: create libvirt network ({{ kvm_cfg.network.name }})"
    when: test_libvirt_network.rc != 0
    shell:
      cmd: |
        virsh net-define /var/tmp/libvirt-network.xml

  - name: "LIBVIRT-SETUP: start libvirt network ({{ kvm_cfg.network.name }})"
    when: test_libvirt_network.rc != 0
    shell: 
      cmd: |
        virsh net-start {{ kvm_cfg.network.name }}

  - name: "LIBVIRT-SETUP: auto-start libvirt network ({{ kvm_cfg.network.name }})"
    when: test_libvirt_network.rc != 0
    shell:
      cmd: |
        virsh net-autostart {{ kvm_cfg.network.name }}

