## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
##
##

---
- hosts: myVirthost

  tasks:

  - include_vars: "{{ item }}"
    with_first_found: "{{ vars_libvirt }}"

  - include_vars: "{{ item }}"
    with_first_found: "{{ vars_rs_profiles }}"

  - include_vars: "{{ item }}"
    with_first_found: "{{ vars_hw_profiles }}"

  - debug:
      var: kvm_cfg

  - debug:
      var: rs_profile[hostvars[item]['h_rsPROF']]
    loop: "{{ groups['myMasters'] }}"

  - debug:
      var: hw_profile[hostvars[item]['h_hwPROF']]
    loop: "{{ groups['myMasters'] }}"

  - name: "LIBVIRT-CREATE-MASTERS: Create ssh directory"
    file:
      path: "{{ kvm_cfg.qcow_dir }}"
      mode: "0775"
      state: directory

  - name: "LIBVIRT-CREATE-MASTERS: determine bootstrap IP address"
    set_fact:
      f_bootstrap_ip: "{{ hostvars[item]['h_pubIP'] }}"
    loop: "{{ groups['myBootstrap'] }}"

  - name: "LIBVIRT-CREATE-MASTERS: test CONFIG SERVER port on bootstrap ({{ f_bootstrap_ip }})"
    wait_for:
      host: "{{ f_bootstrap_ip }}"
      connect_timeout: 5
      delay: 3
      port: "22623"
      sleep: 1
      state: started
      timeout: 1800 

  - name: "LIBVIRT-CREATE-MASTERS: virt-install bootstrap"
    vars:
      p_name:     "{{ hostvars[item]['inventory_hostname_short'] }}"
      p_vmname:   "{{ g_clusterName }}-{{ hostvars[item]['inventory_hostname_short'] }}"
      p_bus:      "{{ hw_profile[hostvars[item]['h_hwPROF']].disk.bus }}"
      p_sparse:   "{{ hw_profile[hostvars[item]['h_hwPROF']].disk.sparse }}"
      p_netdev:   "{{ hw_profile[hostvars[item]['h_hwPROF']].network.model }}"
      p_disksize: "{{ rs_profile[hostvars[item]['h_rsPROF']].disksize }}"
      p_memsize:  "{{ rs_profile[hostvars[item]['h_rsPROF']].memsize }}"
      p_cpu:      "{{ rs_profile[hostvars[item]['h_rsPROF']].vcpus }}"

    shell:
      cmd: |
        virt-install --name="{{ p_vmname }}" \
                     --ram="{{ p_memsize }}" \
                     --disk "{{ kvm_cfg.qcow_dir }}/{{ p_name }}.qcow2,bus={{ p_bus }},sparse={{ p_sparse }},size={{ p_disksize }}" \
                     --check disk_size=off \
                     --network "network={{ kvm_cfg.network.name }},mac={{ hostvars[item]['h_pubMAC'] }},model={{ p_netdev }}" \
                     --graphics vnc \
                     --vcpus {{ p_cpu }} \
                     --boot hd,network,menu=yes \
                     --noautoconsole
    loop: "{{ groups['myMasters'] }}"

