## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
## Playbook Assumptions:
##

---
- hosts: myVirthost

  tasks:

  - include_vars: "{{ item }}"
    with_first_found: "{{ vars_libvirt }}"

  - include_vars: "{{ item }}"
    with_first_found: "{{ vars_reposync }}"

  - debug:
      var: kvm_cfg

  - name: "LIBVIRT-COCKPIT: install cockpit packages"
    yum: name=cockpit,cockpit-machines state=installed

  - name: "LIBVIRT-COCKPIT: create cockpit systemd drop-in directory"
    file:
      path: "/etc/systemd/system/websocket.cockpit.d/"
      mode: "0755"
      owner: "root"
      group: "root"
      state: directory

  - name: "LIBVIRT-COCKPIT: deploy cockpit configuration"
    vars:
      - p_port: "{{ kvm_cfg.cockpit_port }}"
    template:
      src:  "cockpit-listen-conf.j2"
      dest: "/etc/systemd/system/websocket.cockpit.d/listen.conf"
      owner: root
      group: root
      mode: 0644

  - name: "LIBVIRT-COCKPIT: enable system services"
    service: name="{{ item }}" state=restarted enabled=yes masked=no
    with_items:
      - "cockpit"

  - name: "LIBVIRT-COCKPIT: add firewalld services"
    firewalld:
      service: "{{ item }}"
      immediate: yes
      permanent: yes
      state: enabled
    with_items:
      - "cockpit"

  - name: "LIBVIRT-COCKPIT: add firewalld ports"
    firewalld:
      port: "{{ item }}"
      immediate: yes
      permanent: yes
      state: enabled
    with_items:
      - "{{ kvm_cfg.cockpit_port }}/tcp"

# A reminder that if we use a port not natively included by selinux, we need to add it
#   
#  - name: "LIBVIRT-SETUP: add cockpit port to selinux http_port_t"
#  - shell:
#      cmd: |
#        semanage port -a -t http_port_t -p tcp {{ kvm_cfg.cockpit_port }}
