## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
##
##

---
- hosts: myVirthost
  tasks:

  - include_vars: "{{ item }}"
    with_first_found: "{{ vars_libvirt }}"

  - include_vars: "{{ item }}"
    with_first_found: "{{ vars_rs_profiles }}"

  - include_vars: "{{ item }}"
    with_first_found: "{{ vars_hw_profiles }}"

  - debug:
      var: kvm_cfg

  - debug:
      var: rs_profile[hostvars[item]['h_rsPROF']]
    loop: "{{ groups['myBastion'] }}"

  - debug:
      var: hw_profile[hostvars[item]['h_hwPROF']]
    loop: "{{ groups['myBastion'] }}"

  - name: "LIBVIRT-CREATE-BASTION: Create ssh directory"
    file:
      path: "{{ kvm_cfg.qcow_dir }}"
      mode: "0775"
      state: directory

  - name: "LIBVIRT-CREATE-BASTION: deploy kickstart configuration"
    vars:
      - p_diskDevice: "{{ hw_profile[hostvars[item]['h_hwPROF']].disk.dev }}"
    template:
      src: "bastion-kickstart.j2"
      dest: "/var/www/html/ks.cfg"
      owner: root
      group: apache
      mode: 0644
    loop: "{{ groups['myBastion'] }}"

  - name: "LIBVIRT-CREATE-BASTION: virt-install bastion"
    vars:
      p_name:     "{{ hostvars[item]['inventory_hostname_short'] }}"
      p_mac:      "{{ hostvars[item]['h_pubMAC'] }}"
      p_ip:       "{{ hostvars[item]['h_pubIP'] }}"
      p_nm:       "{{ hostvars[item]['g_pubNM'] }}"
      p_gw:       "{{ hostvars[item]['g_pubGW'] }}"
      p_bus:      "{{ hw_profile[hostvars[item]['h_hwPROF']].disk.bus }}"
      p_dns:      "{{ hostvars[item]['g_pubDNS'] }}"
      p_sparse:   "{{ hw_profile[hostvars[item]['h_hwPROF']].disk.sparse }}"
      p_netdev:   "{{ hw_profile[hostvars[item]['h_hwPROF']].network.model }}"
      p_disksize: "{{ rs_profile[hostvars[item]['h_rsPROF']].disksize }}"
      p_memsize:  "{{ rs_profile[hostvars[item]['h_rsPROF']].memsize }}"
      p_cpu:      "{{ rs_profile[hostvars[item]['h_rsPROF']].vcpus }}"
    shell:
      cmd: |
        virt-install --name="{{ p_name }}" \
                     --ram="{{ p_memsize }}" \
                     --disk "{{ kvm_cfg.qcow_dir }}/{{ p_name }}.qcow2,bus={{ p_bus }},sparse={{ p_sparse }},size={{ p_disksize }}" \
                     --check disk_size=off \
                     --location={{ kvm_cfg.iso.dir }}/{{ kvm_cfg.iso.name }} \
                     --extra-args="ks={{ kvm_cfg.ks_url }} ip={{ p_ip }} netmask={{ p_nm }} dns={{ p_dns }} gateway={{ p_gw }}" \
                     --network "network={{ kvm_cfg.network.name }},mac={{ p_mac }},model={{ p_netdev }}" \
                     --graphics vnc \
                     --vcpus {{ p_cpu }} \
                     --boot hd,network,menu=yes \
                     --noreboot
    loop: "{{ groups['myBastion'] }}"

  - name: "LIBVIRT-CREATE-BASTION: Create ssh directory"
    file:
      path: /root/.ssh
      mode: "0700"
      state: directory

  - name: "LIBVIRT-CREATE-BASTION: test ssh key"
    stat: path="/root/.ssh/id_rsa.pub"
    register: test_ssh_key

  - name: "LIBVIRT-CREATE-BASTION: create ssh key"
    command: "ssh-keygen -t rsa -b 2048 -N '' -f /root/.ssh/id_rsa"
    when: test_ssh_key.stat.exists == false

  - name: "LIBVIRT-CREATE-BASTION: inject ssh key to bastion vm"
    shell:
      cmd: |
        virt-customize -d "{{ hostvars[item]['inventory_hostname_short'] }}" \
                       --ssh-inject root:file:/root/.ssh/id_rsa.pub \
                       --selinux-relabel
    loop: "{{ groups['myBastion'] }}"

  - name: "LIBVIRT-CREATE-BASTION: start bastion vm"
    shell:
      cmd: |
        virsh start "{{ hostvars[item]['inventory_hostname_short'] }}"
    loop: "{{ groups['myBastion'] }}"

  - name: "LIBVIRT-CREATE-BASTION: clean out local ssh keys for bastion"
    shell:
      cmd: |
        ssh-keygen -R "{{ hostvars[item]['inventory_hostname'] }}"
        ssh-keygen -R "{{ hostvars[item]['inventory_hostname_short'] }}"
        ssh-keygen -R "{{ hostvars[item]['inventory_hostname_short'] }}.{{ g_clusterName }}.{{ g_publicDomain }}"
        ssh-keygen -R "{{ hostvars[item]['h_pubIP'] }}"
    loop: "{{ groups['myBastion'] }}"
    ignore_errors: yes

  - name: "LIBVIRT-CREATE-BASTION: give bastion a chance to boot"
    wait_for:
      host: "{{ hostvars[item]['h_pubIP'] }}"
      connect_timeout: 5
      delay: 15
      port: 22
      sleep: 1
      state: started
      timeout: 300
    loop: "{{ groups['myBastion'] }}"

  - name: "LIBVIRT-CREATE-BASTION: add ssh keys for bastion"
    shell:
      cmd: |
        ssh-keyscan bastion.ocp.example.com >> /root/.ssh/known_hosts

